USE [master]
GO

/****** Object:  Database [MememberShipDB]    Script Date: 11/17/2022 5:40:15 PM ******/
CREATE DATABASE [MememberShipDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MememberShipDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MememberShipDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MememberShipDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MememberShipDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MememberShipDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MememberShipDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MememberShipDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MememberShipDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MememberShipDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MememberShipDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MememberShipDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MememberShipDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MememberShipDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MememberShipDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MememberShipDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MememberShipDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MememberShipDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MememberShipDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MememberShipDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MememberShipDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MememberShipDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MememberShipDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MememberShipDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MememberShipDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MememberShipDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MememberShipDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MememberShipDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MememberShipDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MememberShipDB] SET  MULTI_USER 
GO

ALTER DATABASE [MememberShipDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MememberShipDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MememberShipDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MememberShipDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MememberShipDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MememberShipDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MememberShipDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MememberShipDB] SET  READ_WRITE 
GO

